org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# Included builds break KGP's annoying "fus" service
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.useFallbackStrategy=false
# https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/2183
org.jetbrains.intellij.platform.testIdeBundledPluginsClasspathExcludes=com.intellij.openRewrite,com.intellij.ja,com.intellij.ko,com.intellij.zh,org.jetbrains.plugins.vue

VERSION_NAME=1.4.0
