

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/diagnostic/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ConflictingAnnotationRoles.kt")
  public void testConflictingAnnotationRoles() {
    run("ConflictingAnnotationRoles.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/aggregation")
  @TestDataPath("$PROJECT_ROOT")
  public class Aggregation {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/aggregation/" + fileName);
    }

    @Test
    public void testAllFilesPresentInAggregation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/aggregation"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ContributedInterfaceCanShareFunctionNamesWithGraphExtension.kt")
    public void testContributedInterfaceCanShareFunctionNamesWithGraphExtension() {
      run("ContributedInterfaceCanShareFunctionNamesWithGraphExtension.kt");
    }

    @Test
    @TestMetadata("ContributesToOnlyPermittedOnInterfacesOrBindingContainers.kt")
    public void testContributesToOnlyPermittedOnInterfacesOrBindingContainers() {
      run("ContributesToOnlyPermittedOnInterfacesOrBindingContainers.kt");
    }

    @Test
    @TestMetadata("ContributionProviderMissingBindingShowsOrigin.kt")
    public void testContributionProviderMissingBindingShowsOrigin() {
      run("ContributionProviderMissingBindingShowsOrigin.kt");
    }

    @Test
    @TestMetadata("ContributionProviderMissingBindingShowsOriginInternal.kt")
    public void testContributionProviderMissingBindingShowsOriginInternal() {
      run("ContributionProviderMissingBindingShowsOriginInternal.kt");
    }

    @Test
    @TestMetadata("CrossModuleContributionProviderHidesImplHint.kt")
    public void testCrossModuleContributionProviderHidesImplHint() {
      run("CrossModuleContributionProviderHidesImplHint.kt");
    }

    @Test
    @TestMetadata("DefaultBinding_Ambiguous.kt")
    public void testDefaultBinding_Ambiguous() {
      run("DefaultBinding_Ambiguous.kt");
    }

    @Test
    @TestMetadata("DefaultBinding_InvalidTypeArg.kt")
    public void testDefaultBinding_InvalidTypeArg() {
      run("DefaultBinding_InvalidTypeArg.kt");
    }

    @Test
    @TestMetadata("DefaultBinding_MustBeSubclassable.kt")
    public void testDefaultBinding_MustBeSubclassable() {
      run("DefaultBinding_MustBeSubclassable.kt");
    }

    @Test
    @TestMetadata("ExposeImplBindingWithoutContributionProviders.kt")
    public void testExposeImplBindingWithoutContributionProviders() {
      run("ExposeImplBindingWithoutContributionProviders.kt");
    }

    @Test
    @TestMetadata("InternalContributionMissingHint.kt")
    public void testInternalContributionMissingHint() {
      run("InternalContributionMissingHint.kt");
    }

    @Test
    @TestMetadata("InternalHintsAreNotVisibleWithoutFriends.kt")
    public void testInternalHintsAreNotVisibleWithoutFriends() {
      run("InternalHintsAreNotVisibleWithoutFriends.kt");
    }

    @Test
    @TestMetadata("MissingBindingInContributionProviderRedirectsToOrigin.kt")
    public void testMissingBindingInContributionProviderRedirectsToOrigin() {
      run("MissingBindingInContributionProviderRedirectsToOrigin.kt");
    }

    @Test
    @TestMetadata("NonPublicContributionDiagnosticSkippedForContributionProviders.kt")
    public void testNonPublicContributionDiagnosticSkippedForContributionProviders() {
      run("NonPublicContributionDiagnosticSkippedForContributionProviders.kt");
    }

    @Test
    @TestMetadata("NonPublicContributionError.kt")
    public void testNonPublicContributionError() {
      run("NonPublicContributionError.kt");
    }

    @Test
    @TestMetadata("NonPublicContributionWarning.kt")
    public void testNonPublicContributionWarning() {
      run("NonPublicContributionWarning.kt");
    }

    @Test
    @TestMetadata("PrivateContributionError.kt")
    public void testPrivateContributionError() {
      run("PrivateContributionError.kt");
    }

    @Test
    @TestMetadata("SimilarBindingsNotReportedWhenMissingBindingTypeIsAny.kt")
    public void testSimilarBindingsNotReportedWhenMissingBindingTypeIsAny() {
      run("SimilarBindingsNotReportedWhenMissingBindingTypeIsAny.kt");
    }

    @Test
    @TestMetadata("SuspiciousScopeWarnings.kt")
    public void testSuspiciousScopeWarnings() {
      run("SuspiciousScopeWarnings.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/api")
  @TestDataPath("$PROJECT_ROOT")
  public class Api {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/api/" + fileName);
    }

    @Test
    public void testAllFilesPresentInApi() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/api"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/api/circuit")
    @TestDataPath("$PROJECT_ROOT")
    public class Circuit {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/api/circuit/" + fileName);
      }

      @Test
      public void testAllFilesPresentInCircuit() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/api/circuit"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("DuplicateCircuitInjects.kt")
      public void testDuplicateCircuitInjects() {
        run("DuplicateCircuitInjects.kt");
      }

      @Test
      @TestMetadata("InvalidAssistedInjection.kt")
      public void testInvalidAssistedInjection() {
        run("InvalidAssistedInjection.kt");
      }

      @Test
      @TestMetadata("InvalidAssistedInjectionMissingFactory.kt")
      public void testInvalidAssistedInjectionMissingFactory() {
        run("InvalidAssistedInjectionMissingFactory.kt");
      }

      @Test
      @TestMetadata("InvalidSupertypes.kt")
      public void testInvalidSupertypes() {
        run("InvalidSupertypes.kt");
      }

      @Test
      @TestMetadata("PresenterClassInvalidParams.kt")
      public void testPresenterClassInvalidParams() {
        run("PresenterClassInvalidParams.kt");
      }

      @Test
      @TestMetadata("PresenterClassMissingInject.kt")
      public void testPresenterClassMissingInject() {
        run("PresenterClassMissingInject.kt");
      }

      @Test
      @TestMetadata("PresenterFunctionImplicitReturnType.kt")
      public void testPresenterFunctionImplicitReturnType() {
        run("PresenterFunctionImplicitReturnType.kt");
      }

      @Test
      @TestMetadata("PresenterFunctionInvalidParams.kt")
      public void testPresenterFunctionInvalidParams() {
        run("PresenterFunctionInvalidParams.kt");
      }

      @Test
      @TestMetadata("PresenterFunctionInvalidReturn.kt")
      public void testPresenterFunctionInvalidReturn() {
        run("PresenterFunctionInvalidReturn.kt");
      }

      @Test
      @TestMetadata("PresenterFunctionMissingReturn.kt")
      public void testPresenterFunctionMissingReturn() {
        run("PresenterFunctionMissingReturn.kt");
      }

      @Test
      @TestMetadata("SubCircuitInvalidSupertypes.kt")
      public void testSubCircuitInvalidSupertypes() {
        run("SubCircuitInvalidSupertypes.kt");
      }

      @Test
      @TestMetadata("SubCircuitTopLevelAssistedFactory.kt")
      public void testSubCircuitTopLevelAssistedFactory() {
        run("SubCircuitTopLevelAssistedFactory.kt");
      }

      @Test
      @TestMetadata("SubCircuitUiFunctionMissingModifier.kt")
      public void testSubCircuitUiFunctionMissingModifier() {
        run("SubCircuitUiFunctionMissingModifier.kt");
      }

      @Test
      @TestMetadata("UiClassInvalidParams.kt")
      public void testUiClassInvalidParams() {
        run("UiClassInvalidParams.kt");
      }

      @Test
      @TestMetadata("UiFunctionInvalidParams.kt")
      public void testUiFunctionInvalidParams() {
        run("UiFunctionInvalidParams.kt");
      }

      @Test
      @TestMetadata("UiFunctionMissingModifier.kt")
      public void testUiFunctionMissingModifier() {
        run("UiFunctionMissingModifier.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/bindingcontainer")
  @TestDataPath("$PROJECT_ROOT")
  public class Bindingcontainer {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/bindingcontainer/" + fileName);
    }

    @Test
    @TestMetadata("AbstractContainersCannotHaveProvides.kt")
    public void testAbstractContainersCannotHaveProvides() {
      run("AbstractContainersCannotHaveProvides.kt");
    }

    @Test
    public void testAllFilesPresentInBindingcontainer() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/bindingcontainer"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CannotAnnotateBothGraphAndContainer.kt")
    public void testCannotAnnotateBothGraphAndContainer() {
      run("CannotAnnotateBothGraphAndContainer.kt");
    }

    @Test
    @TestMetadata("CannotIncludeGenericContainer.kt")
    public void testCannotIncludeGenericContainer() {
      run("CannotIncludeGenericContainer.kt");
    }

    @Test
    @TestMetadata("ContainersCannotExtendOtherContainers.kt")
    public void testContainersCannotExtendOtherContainers() {
      run("ContainersCannotExtendOtherContainers.kt");
    }

    @Test
    @TestMetadata("ContributedContainersMustHaveNoArgConstructors.kt")
    public void testContributedContainersMustHaveNoArgConstructors() {
      run("ContributedContainersMustHaveNoArgConstructors.kt");
    }

    @Test
    @TestMetadata("IllegalTypes.kt")
    public void testIllegalTypes() {
      run("IllegalTypes.kt");
    }

    @Test
    @TestMetadata("IncludedMustBeAContainer.kt")
    public void testIncludedMustBeAContainer() {
      run("IncludedMustBeAContainer.kt");
    }

    @Test
    @TestMetadata("MissingNoArgConstructor.kt")
    public void testMissingNoArgConstructor() {
      run("MissingNoArgConstructor.kt");
    }

    @Test
    @TestMetadata("NoProvidesOnParams.kt")
    public void testNoProvidesOnParams() {
      run("NoProvidesOnParams.kt");
    }

    @Test
    @TestMetadata("SuspiciousIntoSetWithCollection.kt")
    public void testSuspiciousIntoSetWithCollection() {
      run("SuspiciousIntoSetWithCollection.kt");
    }

    @Test
    @TestMetadata("TypeAliasesAreSpecifiedInDiagnostics.kt")
    public void testTypeAliasesAreSpecifiedInDiagnostics() {
      run("TypeAliasesAreSpecifiedInDiagnostics.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/createGraph")
  @TestDataPath("$PROJECT_ROOT")
  public class CreateGraph {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/createGraph/" + fileName);
    }

    @Test
    public void testAllFilesPresentInCreateGraph() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/createGraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CreateGraph_GraphHasFactory.kt")
    public void testCreateGraph_GraphHasFactory() {
      run("CreateGraph_GraphHasFactory.kt");
    }

    @Test
    @TestMetadata("CreateGraph_MustBeGraph.kt")
    public void testCreateGraph_MustBeGraph() {
      run("CreateGraph_MustBeGraph.kt");
    }

    @Test
    @TestMetadata("CreateGraph_MustBeGraphFactory.kt")
    public void testCreateGraph_MustBeGraphFactory() {
      run("CreateGraph_MustBeGraphFactory.kt");
    }

    @Test
    @TestMetadata("CreateGraph_OkCase.kt")
    public void testCreateGraph_OkCase() {
      run("CreateGraph_OkCase.kt");
    }

    @Test
    @TestMetadata("GraphFactoriesMayNotHaveVarargs.kt")
    public void testGraphFactoriesMayNotHaveVarargs() {
      run("GraphFactoriesMayNotHaveVarargs.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/cycles")
  @TestDataPath("$PROJECT_ROOT")
  public class Cycles {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/cycles/" + fileName);
    }

    @Test
    public void testAllFilesPresentInCycles() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/cycles"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CyclesShouldFailAcrossMultipleGraphs.kt")
    public void testCyclesShouldFailAcrossMultipleGraphs() {
      run("CyclesShouldFailAcrossMultipleGraphs.kt");
    }

    @Test
    @TestMetadata("MixedParallelDependencyCycles.kt")
    public void testMixedParallelDependencyCycles() {
      run("MixedParallelDependencyCycles.kt");
    }

    @Test
    @TestMetadata("ProvidesSccShouldNotCrashReporter.kt")
    public void testProvidesSccShouldNotCrashReporter() {
      run("ProvidesSccShouldNotCrashReporter.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph")
  @TestDataPath("$PROJECT_ROOT")
  public class Dependencygraph {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/" + fileName);
    }

    @Test
    @TestMetadata("AllDuplicateBindingsAreReported.kt")
    public void testAllDuplicateBindingsAreReported() {
      run("AllDuplicateBindingsAreReported.kt");
    }

    @Test
    public void testAllFilesPresentInDependencygraph() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AsContributionCannotWorkOnContributedExtensions.kt")
    public void testAsContributionCannotWorkOnContributedExtensions() {
      run("AsContributionCannotWorkOnContributedExtensions.kt");
    }

    @Test
    @TestMetadata("AsContributionCannotWorkOnContributedExtensionsMultiModule.kt")
    public void testAsContributionCannotWorkOnContributedExtensionsMultiModule() {
      run("AsContributionCannotWorkOnContributedExtensionsMultiModule.kt");
    }

    @Test
    @TestMetadata("AssistedTypesCannotBeDirectlyQualified.kt")
    public void testAssistedTypesCannotBeDirectlyQualified() {
      run("AssistedTypesCannotBeDirectlyQualified.kt");
    }

    @Test
    @TestMetadata("AssistedTypesCannotBeProvidedWithoutQualifiers.kt")
    public void testAssistedTypesCannotBeProvidedWithoutQualifiers() {
      run("AssistedTypesCannotBeProvidedWithoutQualifiers.kt");
    }

    @Test
    @TestMetadata("ClassBindingsCannotSatisfyNullable.kt")
    public void testClassBindingsCannotSatisfyNullable() {
      run("ClassBindingsCannotSatisfyNullable.kt");
    }

    @Test
    @TestMetadata("ConfigurableMaxIrErrors.kt")
    public void testConfigurableMaxIrErrors() {
      run("ConfigurableMaxIrErrors.kt");
    }

    @Test
    @TestMetadata("DependencyCycleAdvice.kt")
    public void testDependencyCycleAdvice() {
      run("DependencyCycleAdvice.kt");
    }

    @Test
    @TestMetadata("DependencyCycleAdviceWithSuspendProviders.kt")
    public void testDependencyCycleAdviceWithSuspendProviders() {
      run("DependencyCycleAdviceWithSuspendProviders.kt");
    }

    @Test
    @TestMetadata("DependencyGraphFactory_ParamsCannotBeScoped.kt")
    public void testDependencyGraphFactory_ParamsCannotBeScoped() {
      run("DependencyGraphFactory_ParamsCannotBeScoped.kt");
    }

    @Test
    @TestMetadata("DependencyGraphFactory_ProvidesParamCannotBeIntrinsic.kt")
    public void testDependencyGraphFactory_ProvidesParamCannotBeIntrinsic() {
      run("DependencyGraphFactory_ProvidesParamCannotBeIntrinsic.kt");
    }

    @Test
    @TestMetadata("DoNotSuggestSimilarBindingSubtypesForAny.kt")
    public void testDoNotSuggestSimilarBindingSubtypesForAny() {
      run("DoNotSuggestSimilarBindingSubtypesForAny.kt");
    }

    @Test
    @TestMetadata("DoNotSuggestSimilarBindingsForMultibindingElements.kt")
    public void testDoNotSuggestSimilarBindingsForMultibindingElements() {
      run("DoNotSuggestSimilarBindingsForMultibindingElements.kt");
    }

    @Test
    @TestMetadata("GraphAccessorsCannotBeMutable.kt")
    public void testGraphAccessorsCannotBeMutable() {
      run("GraphAccessorsCannotBeMutable.kt");
    }

    @Test
    @TestMetadata("GraphPrivateAccessorIsAnError.kt")
    public void testGraphPrivateAccessorIsAnError() {
      run("GraphPrivateAccessorIsAnError.kt");
    }

    @Test
    @TestMetadata("GraphPrivateDependencyGraphFactoryParam.kt")
    public void testGraphPrivateDependencyGraphFactoryParam() {
      run("GraphPrivateDependencyGraphFactoryParam.kt");
    }

    @Test
    @TestMetadata("GraphsCannotDirectlyExtendOtherGraphs.kt")
    public void testGraphsCannotDirectlyExtendOtherGraphs() {
      run("GraphsCannotDirectlyExtendOtherGraphs.kt");
    }

    @Test
    @TestMetadata("InternalBindings.kt")
    public void testInternalBindings() {
      run("InternalBindings.kt");
    }

    @Test
    @TestMetadata("MismatchedSingleInScopesDisambiguateSameNameScopes.kt")
    public void testMismatchedSingleInScopesDisambiguateSameNameScopes() {
      run("MismatchedSingleInScopesDisambiguateSameNameScopes.kt");
    }

    @Test
    @TestMetadata("MissingBindingHintsShouldReportInternalOnlyIfInternal.kt")
    public void testMissingBindingHintsShouldReportInternalOnlyIfInternal() {
      run("MissingBindingHintsShouldReportInternalOnlyIfInternal.kt");
    }

    @Test
    @TestMetadata("MixedCycleParams.kt")
    public void testMixedCycleParams() {
      run("MixedCycleParams.kt");
    }

    @Test
    @TestMetadata("MultipleGraphAnnotationsAreAnError.kt")
    public void testMultipleGraphAnnotationsAreAnError() {
      run("MultipleGraphAnnotationsAreAnError.kt");
    }

    @Test
    @TestMetadata("MultipleMissingDeps.kt")
    public void testMultipleMissingDeps() {
      run("MultipleMissingDeps.kt");
    }

    @Test
    @TestMetadata("ParameterlessBindsConstructorCycle.kt")
    public void testParameterlessBindsConstructorCycle() {
      run("ParameterlessBindsConstructorCycle.kt");
    }

    @Test
    @TestMetadata("ParameterlessBindsDuplicateBinding.kt")
    public void testParameterlessBindsDuplicateBinding() {
      run("ParameterlessBindsDuplicateBinding.kt");
    }

    @Test
    @TestMetadata("ParameterlessBindsExternalFactoryUnavailable.kt")
    public void testParameterlessBindsExternalFactoryUnavailable() {
      run("ParameterlessBindsExternalFactoryUnavailable.kt");
    }

    @Test
    @TestMetadata("RuntimeTracingRequiresGraphFactory.kt")
    public void testRuntimeTracingRequiresGraphFactory() {
      run("RuntimeTracingRequiresGraphFactory.kt");
    }

    @Test
    @TestMetadata("RuntimeTracingRequiresTracerFactoryInput.kt")
    public void testRuntimeTracingRequiresTracerFactoryInput() {
      run("RuntimeTracingRequiresTracerFactoryInput.kt");
    }

    @Test
    @TestMetadata("SuspendDependencyCycleAdvice.kt")
    public void testSuspendDependencyCycleAdvice() {
      run("SuspendDependencyCycleAdvice.kt");
    }

    @Test
    @TestMetadata("UnusedGraphInputsAreReported.kt")
    public void testUnusedGraphInputsAreReported() {
      run("UnusedGraphInputsAreReported.kt");
    }

    @Test
    @TestMetadata("UnusedGraphInputsInGraphExtensionAreReported.kt")
    public void testUnusedGraphInputsInGraphExtensionAreReported() {
      run("UnusedGraphInputsInGraphExtensionAreReported.kt");
    }

    @Test
    @TestMetadata("UsefulHintsForMissingImplDeps.kt")
    public void testUsefulHintsForMissingImplDeps() {
      run("UsefulHintsForMissingImplDeps.kt");
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph/dynamic")
    @TestDataPath("$PROJECT_ROOT")
    public class Dynamic {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/dynamic/" + fileName);
      }

      @Test
      public void testAllFilesPresentInDynamic() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph/dynamic"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("CreateDynamicGraphArgumentDiagnostics.kt")
      public void testCreateDynamicGraphArgumentDiagnostics() {
        run("CreateDynamicGraphArgumentDiagnostics.kt");
      }

      @Test
      @TestMetadata("CreateDynamicGraphCannotBeInLocalClasses.kt")
      public void testCreateDynamicGraphCannotBeInLocalClasses() {
        run("CreateDynamicGraphCannotBeInLocalClasses.kt");
      }

      @Test
      @TestMetadata("DuplicateBindingsInDynamicGraphReportTheCallLocation.kt")
      public void testDuplicateBindingsInDynamicGraphReportTheCallLocation() {
        run("DuplicateBindingsInDynamicGraphReportTheCallLocation.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph/extensions")
    @TestDataPath("$PROJECT_ROOT")
    public class Extensions {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/extensions/" + fileName);
      }

      @Test
      @TestMetadata("AdhocGraphExtensionFactoriesAreNotSupported.kt")
      public void testAdhocGraphExtensionFactoriesAreNotSupported() {
        run("AdhocGraphExtensionFactoriesAreNotSupported.kt");
      }

      @Test
      public void testAllFilesPresentInExtensions() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph/extensions"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("DeepGraphExtensionChainEmitsWarning.kt")
      public void testDeepGraphExtensionChainEmitsWarning() {
        run("DeepGraphExtensionChainEmitsWarning.kt");
      }

      @Test
      @TestMetadata("ExcludedPublicGraphExtensionFactoryHasNoInternalHint.kt")
      public void testExcludedPublicGraphExtensionFactoryHasNoInternalHint() {
        run("ExcludedPublicGraphExtensionFactoryHasNoInternalHint.kt");
      }

      @Test
      @TestMetadata("ExtensionAccessorsCannotHaveParameters.kt")
      public void testExtensionAccessorsCannotHaveParameters() {
        run("ExtensionAccessorsCannotHaveParameters.kt");
      }

      @Test
      @TestMetadata("ExtensionsWithFactoriesMustUseThem.kt")
      public void testExtensionsWithFactoriesMustUseThem() {
        run("ExtensionsWithFactoriesMustUseThem.kt");
      }

      @Test
      @TestMetadata("GraphExtensionFactory_ParamsCannotBeScoped.kt")
      public void testGraphExtensionFactory_ParamsCannotBeScoped() {
        run("GraphExtensionFactory_ParamsCannotBeScoped.kt");
      }

      @Test
      @TestMetadata("GraphExtensionFactory_ProvidesParamCannotBeIntrinsic.kt")
      public void testGraphExtensionFactory_ProvidesParamCannotBeIntrinsic() {
        run("GraphExtensionFactory_ProvidesParamCannotBeIntrinsic.kt");
      }

      @Test
      @TestMetadata("GraphExtensionFactory_WrongAnnotation.kt")
      public void testGraphExtensionFactory_WrongAnnotation() {
        run("GraphExtensionFactory_WrongAnnotation.kt");
      }

      @Test
      @TestMetadata("GraphPrivateBindingNotVisibleToChild.kt")
      public void testGraphPrivateBindingNotVisibleToChild() {
        run("GraphPrivateBindingNotVisibleToChild.kt");
      }

      @Test
      @TestMetadata("GraphPrivateBindingNotVisibleToGrandchild.kt")
      public void testGraphPrivateBindingNotVisibleToGrandchild() {
        run("GraphPrivateBindingNotVisibleToGrandchild.kt");
      }

      @Test
      @TestMetadata("GraphPrivateGraphExtensionFactoryParam.kt")
      public void testGraphPrivateGraphExtensionFactoryParam() {
        run("GraphPrivateGraphExtensionFactoryParam.kt");
      }

      @Test
      @TestMetadata("GraphPrivateSourceNotLeakedViaBindsAlias.kt")
      public void testGraphPrivateSourceNotLeakedViaBindsAlias() {
        run("GraphPrivateSourceNotLeakedViaBindsAlias.kt");
      }

      @Test
      @TestMetadata("OverridesAreTypeChecked.kt")
      public void testOverridesAreTypeChecked() {
        run("OverridesAreTypeChecked.kt");
      }

      @Test
      @TestMetadata("ParentDuplicateBindingsUsedOnlyByChild.kt")
      public void testParentDuplicateBindingsUsedOnlyByChild() {
        run("ParentDuplicateBindingsUsedOnlyByChild.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph/leniency")
    @TestDataPath("$PROJECT_ROOT")
    public class Leniency {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/leniency/" + fileName);
      }

      @Test
      public void testAllFilesPresentInLeniency() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph/leniency"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("SomeUnusedAndSomeUsed.kt")
      public void testSomeUnusedAndSomeUsed() {
        run("SomeUnusedAndSomeUsed.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph/optional")
    @TestDataPath("$PROJECT_ROOT")
    public class Optional {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/optional/" + fileName);
      }

      @Test
      public void testAllFilesPresentInOptional() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph/optional"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("DisabledResultsInMissingBindingMultiModule.kt")
      public void testDisabledResultsInMissingBindingMultiModule() {
        run("DisabledResultsInMissingBindingMultiModule.kt");
      }

      @Test
      @TestMetadata("DisabledResultsInMissingBindings.kt")
      public void testDisabledResultsInMissingBindings() {
        run("DisabledResultsInMissingBindings.kt");
      }

      @Test
      @TestMetadata("DisabledResultsInMissingBindingsEvenWithAnnotation.kt")
      public void testDisabledResultsInMissingBindingsEvenWithAnnotation() {
        run("DisabledResultsInMissingBindingsEvenWithAnnotation.kt");
      }

      @Test
      @TestMetadata("OptionalAccessorDiagnostics.kt")
      public void testOptionalAccessorDiagnostics() {
        run("OptionalAccessorDiagnostics.kt");
      }

      @Test
      @TestMetadata("OptionalBindingErrorIfDisabled.kt")
      public void testOptionalBindingErrorIfDisabled() {
        run("OptionalBindingErrorIfDisabled.kt");
      }

      @Test
      @TestMetadata("OptionalBindingIsNotAllowedOnInjectors.kt")
      public void testOptionalBindingIsNotAllowedOnInjectors() {
        run("OptionalBindingIsNotAllowedOnInjectors.kt");
      }

      @Test
      @TestMetadata("OptionalBindingParamRequiresDefaultValue.kt")
      public void testOptionalBindingParamRequiresDefaultValue() {
        run("OptionalBindingParamRequiresDefaultValue.kt");
      }

      @Test
      @TestMetadata("OptionalBindingParamWarningIfDefault.kt")
      public void testOptionalBindingParamWarningIfDefault() {
        run("OptionalBindingParamWarningIfDefault.kt");
      }

      @Test
      @TestMetadata("RequiredAnnotationResultsInMissingBindingMultiModule.kt")
      public void testRequiredAnnotationResultsInMissingBindingMultiModule() {
        run("RequiredAnnotationResultsInMissingBindingMultiModule.kt");
      }

      @Test
      @TestMetadata("RequiredAnnotationResultsInMissingBindings.kt")
      public void testRequiredAnnotationResultsInMissingBindings() {
        run("RequiredAnnotationResultsInMissingBindings.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/dependencygraph/sharding")
    @TestDataPath("$PROJECT_ROOT")
    public class Sharding {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/dependencygraph/sharding/" + fileName);
      }

      @Test
      public void testAllFilesPresentInSharding() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/dependencygraph/sharding"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("ShardingThresholdNotReachedWarning.kt")
      public void testShardingThresholdNotReachedWarning() {
        run("ShardingThresholdNotReachedWarning.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/functioninject")
  @TestDataPath("$PROJECT_ROOT")
  public class Functioninject {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/functioninject/" + fileName);
    }

    @Test
    public void testAllFilesPresentInFunctioninject() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/functioninject"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AssistedUnderscoreContextParamRequiresIdentifier.kt")
    public void testAssistedUnderscoreContextParamRequiresIdentifier() {
      run("AssistedUnderscoreContextParamRequiresIdentifier.kt");
    }

    @Test
    @TestMetadata("CannotBeScoped.kt")
    public void testCannotBeScoped() {
      run("CannotBeScoped.kt");
    }

    @Test
    @TestMetadata("CannotHaveExtensionReceivers.kt")
    public void testCannotHaveExtensionReceivers() {
      run("CannotHaveExtensionReceivers.kt");
    }

    @Test
    @TestMetadata("CannotHaveReifiedTypeArgs.kt")
    public void testCannotHaveReifiedTypeArgs() {
      run("CannotHaveReifiedTypeArgs.kt");
    }

    @Test
    @TestMetadata("ContextParamsCannotBeOptional.kt")
    public void testContextParamsCannotBeOptional() {
      run("ContextParamsCannotBeOptional.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/graph")
  @TestDataPath("$PROJECT_ROOT")
  public class Graph {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/graph/" + fileName);
    }

    @Test
    public void testAllFilesPresentInGraph() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/graph"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("LazyAssistedFactoryGraphAccessor.kt")
    public void testLazyAssistedFactoryGraphAccessor() {
      run("LazyAssistedFactoryGraphAccessor.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/inject")
  @TestDataPath("$PROJECT_ROOT")
  public class Inject {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/inject/" + fileName);
    }

    @Test
    public void testAllFilesPresentInInject() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/inject"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AmbiguousPrimaryConstructor.kt")
    public void testAmbiguousPrimaryConstructor() {
      run("AmbiguousPrimaryConstructor.kt");
    }

    @Test
    @TestMetadata("CannotMixProviderOfLazyTypes.kt")
    public void testCannotMixProviderOfLazyTypes() {
      run("CannotMixProviderOfLazyTypes.kt");
    }

    @Test
    @TestMetadata("ConflictingProvidesAndClassScopes.kt")
    public void testConflictingProvidesAndClassScopes() {
      run("ConflictingProvidesAndClassScopes.kt");
    }

    @Test
    @TestMetadata("DesugaredProviderWarning.kt")
    public void testDesugaredProviderWarning() {
      run("DesugaredProviderWarning.kt");
    }

    @Test
    @TestMetadata("InjectingAPlainObjectIsSus.kt")
    public void testInjectingAPlainObjectIsSus() {
      run("InjectingAPlainObjectIsSus.kt");
    }

    @Test
    @TestMetadata("InjectingContributesClassWithoutExposeImplBinding.kt")
    public void testInjectingContributesClassWithoutExposeImplBinding() {
      run("InjectingContributesClassWithoutExposeImplBinding.kt");
    }

    @Test
    @TestMetadata("InjectingContributesClassWithoutExposeImplBindingQualified.kt")
    public void testInjectingContributesClassWithoutExposeImplBindingQualified() {
      run("InjectingContributesClassWithoutExposeImplBindingQualified.kt");
    }

    @Test
    @TestMetadata("ProvidingAConstructorInjectedTypeHasASpecificWarning.kt")
    public void testProvidingAConstructorInjectedTypeHasASpecificWarning() {
      run("ProvidingAConstructorInjectedTypeHasASpecificWarning.kt");
    }

    @Test
    @TestMetadata("SuggestInjectClassOnSingleContructor.kt")
    public void testSuggestInjectClassOnSingleContructor() {
      run("SuggestInjectClassOnSingleContructor.kt");
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/inject/assisted")
    @TestDataPath("$PROJECT_ROOT")
    public class Assisted {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/inject/assisted/" + fileName);
      }

      @Test
      public void testAllFilesPresentInAssisted() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/inject/assisted"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeAnnotationClasses.kt")
      public void testAssistedFactoriesCannotBeAnnotationClasses() {
        run("AssistedFactoriesCannotBeAnnotationClasses.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeAnnotationObjects.kt")
      public void testAssistedFactoriesCannotBeAnnotationObjects() {
        run("AssistedFactoriesCannotBeAnnotationObjects.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeEnums.kt")
      public void testAssistedFactoriesCannotBeEnums() {
        run("AssistedFactoriesCannotBeEnums.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeFinal.kt")
      public void testAssistedFactoriesCannotBeFinal() {
        run("AssistedFactoriesCannotBeFinal.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeLocal.kt")
      public void testAssistedFactoriesCannotBeLocal() {
        run("AssistedFactoriesCannotBeLocal.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBePrivate.kt")
      public void testAssistedFactoriesCannotBePrivate() {
        run("AssistedFactoriesCannotBePrivate.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeProtected.kt")
      public void testAssistedFactoriesCannotBeProtected() {
        run("AssistedFactoriesCannotBeProtected.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeSealedClasses.kt")
      public void testAssistedFactoriesCannotBeSealedClasses() {
        run("AssistedFactoriesCannotBeSealedClasses.kt");
      }

      @Test
      @TestMetadata("AssistedFactoriesCannotBeSealedInterfaces.kt")
      public void testAssistedFactoriesCannotBeSealedInterfaces() {
        run("AssistedFactoriesCannotBeSealedInterfaces.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryExtraParamReportsOnParam.kt")
      public void testAssistedFactoryExtraParamReportsOnParam() {
        run("AssistedFactoryExtraParamReportsOnParam.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryMustTargetAssistedInjectTypesButMissingConstructor.kt")
      public void testAssistedFactoryMustTargetAssistedInjectTypesButMissingConstructor() {
        run("AssistedFactoryMustTargetAssistedInjectTypesButMissingConstructor.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryMustTargetAssistedInjectTypesButMissingReturnType.kt")
      public void testAssistedFactoryMustTargetAssistedInjectTypesButMissingReturnType() {
        run("AssistedFactoryMustTargetAssistedInjectTypesButMissingReturnType.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryMustTargetAssistedInjectTypesWithMatchingParameters.kt")
      public void testAssistedFactoryMustTargetAssistedInjectTypesWithMatchingParameters() {
        run("AssistedFactoryMustTargetAssistedInjectTypesWithMatchingParameters.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryWithMissingSAM.kt")
      public void testAssistedFactoryWithMissingSAM() {
        run("AssistedFactoryWithMissingSAM.kt");
      }

      @Test
      @TestMetadata("AssistedFactoryWithMultipleSAMs.kt")
      public void testAssistedFactoryWithMultipleSAMs() {
        run("AssistedFactoryWithMultipleSAMs.kt");
      }

      @Test
      @TestMetadata("ContributesAnnotationsNotAllowedOnAssistedInjectClasses.kt")
      public void testContributesAnnotationsNotAllowedOnAssistedInjectClasses() {
        run("ContributesAnnotationsNotAllowedOnAssistedInjectClasses.kt");
      }

      @Test
      @TestMetadata("InheritedAssistedFactoryParamMismatchReportsOnFactory.kt")
      public void testInheritedAssistedFactoryParamMismatchReportsOnFactory() {
        run("InheritedAssistedFactoryParamMismatchReportsOnFactory.kt");
      }

      @Test
      @TestMetadata("InjectingAssistedInjectClassesIsAnError.kt")
      public void testInjectingAssistedInjectClassesIsAnError() {
        run("InjectingAssistedInjectClassesIsAnError.kt");
      }

      @Test
      @TestMetadata("LazyAssistedFactoryInjection.kt")
      public void testLazyAssistedFactoryInjection() {
        run("LazyAssistedFactoryInjection.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/inject/function")
    @TestDataPath("$PROJECT_ROOT")
    public class Function {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/inject/function/" + fileName);
      }

      @Test
      public void testAllFilesPresentInFunction() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/inject/function"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("LazyAssistedFactoryFunctionInjection.kt")
      public void testLazyAssistedFactoryFunctionInjection() {
        run("LazyAssistedFactoryFunctionInjection.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/inject/member")
    @TestDataPath("$PROJECT_ROOT")
    public class Member {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/inject/member/" + fileName);
      }

      @Test
      public void testAllFilesPresentInMember() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/inject/member"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("FunctionMemberInjectionCannotHaveDefaultValues.kt")
      public void testFunctionMemberInjectionCannotHaveDefaultValues() {
        run("FunctionMemberInjectionCannotHaveDefaultValues.kt");
      }

      @Test
      @TestMetadata("FunctionMemberInjectsCannotHaveTypeParams.kt")
      public void testFunctionMemberInjectsCannotHaveTypeParams() {
        run("FunctionMemberInjectsCannotHaveTypeParams.kt");
      }

      @Test
      @TestMetadata("HasMemberInjectionDiagnostics.kt")
      public void testHasMemberInjectionDiagnostics() {
        run("HasMemberInjectionDiagnostics.kt");
      }

      @Test
      @TestMetadata("MemberInjectedShowsInjectFunctionInTrace.kt")
      public void testMemberInjectedShowsInjectFunctionInTrace() {
        run("MemberInjectedShowsInjectFunctionInTrace.kt");
      }

      @Test
      @TestMetadata("MembersInjectorParameterWithNoDefaultShouldError.kt")
      public void testMembersInjectorParameterWithNoDefaultShouldError() {
        run("MembersInjectorParameterWithNoDefaultShouldError.kt");
      }

      @Test
      @TestMetadata("MissingMemberInjectionShouldFailBinding1.kt")
      public void testMissingMemberInjectionShouldFailBinding1() {
        run("MissingMemberInjectionShouldFailBinding1.kt");
      }

      @Test
      @TestMetadata("MissingMemberInjectionShouldFailBinding2.kt")
      public void testMissingMemberInjectionShouldFailBinding2() {
        run("MissingMemberInjectionShouldFailBinding2.kt");
      }

      @Test
      @TestMetadata("MultipleSubtypesWithCommonParentMemberInjectionsDoNotWarnAboutDupes.kt")
      public void testMultipleSubtypesWithCommonParentMemberInjectionsDoNotWarnAboutDupes() {
        run("MultipleSubtypesWithCommonParentMemberInjectionsDoNotWarnAboutDupes.kt");
      }

      @Test
      @TestMetadata("UnnecessaryMemberInjectShouldError.kt")
      public void testUnnecessaryMemberInjectShouldError() {
        run("UnnecessaryMemberInjectShouldError.kt");
      }

      @Test
      @TestMetadata("UnnecessaryMemberInjectShouldErrorInSeparateModule.kt")
      public void testUnnecessaryMemberInjectShouldErrorInSeparateModule() {
        run("UnnecessaryMemberInjectShouldErrorInSeparateModule.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/interop")
  @TestDataPath("$PROJECT_ROOT")
  public class Interop {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/interop/" + fileName);
    }

    @Test
    public void testAllFilesPresentInInterop() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/interop"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/diagnostic/interop/dagger")
    @TestDataPath("$PROJECT_ROOT")
    public class Dagger {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/diagnostic/interop/dagger/" + fileName);
      }

      @Test
      public void testAllFilesPresentInDagger() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/interop/dagger"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("BindsOptionalOfDiagnostics.kt")
      public void testBindsOptionalOfDiagnostics() {
        run("BindsOptionalOfDiagnostics.kt");
      }

      @Test
      @TestMetadata("DaggerModuleSubcomponentsIsIgnored.kt")
      public void testDaggerModuleSubcomponentsIsIgnored() {
        run("DaggerModuleSubcomponentsIsIgnored.kt");
      }

      @Test
      @TestMetadata("DoNotSuggestMovingInjectAnnotationToClassWhenUsingJavaxOrJakartaInject.kt")
      public void testDoNotSuggestMovingInjectAnnotationToClassWhenUsingJavaxOrJakartaInject() {
        run("DoNotSuggestMovingInjectAnnotationToClassWhenUsingJavaxOrJakartaInject.kt");
      }

      @Test
      @TestMetadata("MemberInjectionQualifiersAreLookedUp.kt")
      public void testMemberInjectionQualifiersAreLookedUp() {
        run("MemberInjectionQualifiersAreLookedUp.kt");
      }

      @Test
      @TestMetadata("ModulesWithConstructorInjectedFields.kt")
      public void testModulesWithConstructorInjectedFields() {
        run("ModulesWithConstructorInjectedFields.kt");
      }

      @Test
      @TestMetadata("PositionalAnnotationArgsError.kt")
      public void testPositionalAnnotationArgsError() {
        run("PositionalAnnotationArgsError.kt");
      }

      @Test
      @TestMetadata("PositionalAnnotationArgsWarning.kt")
      public void testPositionalAnnotationArgsWarning() {
        run("PositionalAnnotationArgsWarning.kt");
      }

      @Test
      @TestMetadata("UnprocessedUpstreamMemberInjection.kt")
      public void testUnprocessedUpstreamMemberInjection() {
        run("UnprocessedUpstreamMemberInjection.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/multibindings")
  @TestDataPath("$PROJECT_ROOT")
  public class Multibindings {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/multibindings/" + fileName);
    }

    @Test
    public void testAllFilesPresentInMultibindings() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/multibindings"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("BindingCallableMultibindingDiagnostics.kt")
    public void testBindingCallableMultibindingDiagnostics() {
      run("BindingCallableMultibindingDiagnostics.kt");
    }

    @Test
    @TestMetadata("DaggerLazyClassKeyIsUnsupported.kt")
    public void testDaggerLazyClassKeyIsUnsupported() {
      run("DaggerLazyClassKeyIsUnsupported.kt");
    }

    @Test
    @TestMetadata("DuplicateMapKeys.kt")
    public void testDuplicateMapKeys() {
      run("DuplicateMapKeys.kt");
    }

    @Test
    @TestMetadata("ElementsIntoSetMustHaveTypeArg.kt")
    public void testElementsIntoSetMustHaveTypeArg() {
      run("ElementsIntoSetMustHaveTypeArg.kt");
    }

    @Test
    @TestMetadata("EmptyMultibindingFunctionType.kt")
    public void testEmptyMultibindingFunctionType() {
      run("EmptyMultibindingFunctionType.kt");
    }

    @Test
    @TestMetadata("ImplicitClassKeyDiagnostics.kt")
    public void testImplicitClassKeyDiagnostics() {
      run("ImplicitClassKeyDiagnostics.kt");
    }

    @Test
    @TestMetadata("IncompatibleMapValueType.kt")
    public void testIncompatibleMapValueType() {
      run("IncompatibleMapValueType.kt");
    }

    @Test
    @TestMetadata("MapKeyDiagnostics.kt")
    public void testMapKeyDiagnostics() {
      run("MapKeyDiagnostics.kt");
    }

    @Test
    @TestMetadata("MapKeyRequiresContributesIntoMap.kt")
    public void testMapKeyRequiresContributesIntoMap() {
      run("MapKeyRequiresContributesIntoMap.kt");
    }

    @Test
    @TestMetadata("MissingBindingFunctionType.kt")
    public void testMissingBindingFunctionType() {
      run("MissingBindingFunctionType.kt");
    }

    @Test
    @TestMetadata("SuspiciousUnusedMultibinding.kt")
    public void testSuspiciousUnusedMultibinding() {
      run("SuspiciousUnusedMultibinding.kt");
    }

    @Test
    @TestMetadata("SuspiciousUnusedMultibindingInChildScope.kt")
    public void testSuspiciousUnusedMultibindingInChildScope() {
      run("SuspiciousUnusedMultibindingInChildScope.kt");
    }

    @Test
    @TestMetadata("SuspiciousUnusedMultibindingSet.kt")
    public void testSuspiciousUnusedMultibindingSet() {
      run("SuspiciousUnusedMultibindingSet.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/provides")
  @TestDataPath("$PROJECT_ROOT")
  public class Provides {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/provides/" + fileName);
    }

    @Test
    public void testAllFilesPresentInProvides() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/provides"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AssistedParametersAreNotSupportedOnProvides.kt")
    public void testAssistedParametersAreNotSupportedOnProvides() {
      run("AssistedParametersAreNotSupportedOnProvides.kt");
    }

    @Test
    @TestMetadata("BindsMayNotHaveScopes.kt")
    public void testBindsMayNotHaveScopes() {
      run("BindsMayNotHaveScopes.kt");
    }

    @Test
    @TestMetadata("BindsNonThisReturningBodiesShouldError_AbstractClass.kt")
    public void testBindsNonThisReturningBodiesShouldError_AbstractClass() {
      run("BindsNonThisReturningBodiesShouldError_AbstractClass.kt");
    }

    @Test
    @TestMetadata("BindsNonThisReturningBodiesShouldError_Interface.kt")
    public void testBindsNonThisReturningBodiesShouldError_Interface() {
      run("BindsNonThisReturningBodiesShouldError_Interface.kt");
    }

    @Test
    @TestMetadata("Binds_Interface_OkCase.kt")
    public void testBinds_Interface_OkCase() {
      run("Binds_Interface_OkCase.kt");
    }

    @Test
    @TestMetadata("Binds_interface_BoundTypesMustBeSubtypes.kt")
    public void testBinds_interface_BoundTypesMustBeSubtypes() {
      run("Binds_interface_BoundTypesMustBeSubtypes.kt");
    }

    @Test
    @TestMetadata("Binds_interface_SameTypesCannotHaveSameQualifiers.kt")
    public void testBinds_interface_SameTypesCannotHaveSameQualifiers() {
      run("Binds_interface_SameTypesCannotHaveSameQualifiers.kt");
    }

    @Test
    @TestMetadata("DaggerReusable_IsUnsupported.kt")
    public void testDaggerReusable_IsUnsupported() {
      run("DaggerReusable_IsUnsupported.kt");
    }

    @Test
    @TestMetadata("GraphPrivateOnNonProvideIsAnError.kt")
    public void testGraphPrivateOnNonProvideIsAnError() {
      run("GraphPrivateOnNonProvideIsAnError.kt");
    }

    @Test
    @TestMetadata("InlineProviderDiagnostics.kt")
    public void testInlineProviderDiagnostics() {
      run("InlineProviderDiagnostics.kt");
    }

    @Test
    @TestMetadata("LazyAssistedFactoryProvides.kt")
    public void testLazyAssistedFactoryProvides() {
      run("LazyAssistedFactoryProvides.kt");
    }

    @Test
    @TestMetadata("ParameterlessBindsContributionProviders.kt")
    public void testParameterlessBindsContributionProviders() {
      run("ParameterlessBindsContributionProviders.kt");
    }

    @Test
    @TestMetadata("ParameterlessBindsDiagnostics.kt")
    public void testParameterlessBindsDiagnostics() {
      run("ParameterlessBindsDiagnostics.kt");
    }

    @Test
    @TestMetadata("PrivateProviderOption_Error.kt")
    public void testPrivateProviderOption_Error() {
      run("PrivateProviderOption_Error.kt");
    }

    @Test
    @TestMetadata("PrivateProviderOption_IdeWarn.kt")
    public void testPrivateProviderOption_IdeWarn() {
      run("PrivateProviderOption_IdeWarn.kt");
    }

    @Test
    @TestMetadata("PrivateProviderOption_None.kt")
    public void testPrivateProviderOption_None() {
      run("PrivateProviderOption_None.kt");
    }

    @Test
    @TestMetadata("PrivateProvidesPropertiesUnsupported.kt")
    public void testPrivateProvidesPropertiesUnsupported() {
      run("PrivateProvidesPropertiesUnsupported.kt");
    }

    @Test
    @TestMetadata("ProvidedInjectedClassesWithMatchingTypeKeysAreREportedAsWarnings_Qualified.kt")
    public void testProvidedInjectedClassesWithMatchingTypeKeysAreREportedAsWarnings_Qualified() {
      run("ProvidedInjectedClassesWithMatchingTypeKeysAreREportedAsWarnings_Qualified.kt");
    }

    @Test
    @TestMetadata("ProvidedInjectedClassesWithMatchingTypeKeysAreReportedAsWarnings.kt")
    public void testProvidedInjectedClassesWithMatchingTypeKeysAreReportedAsWarnings() {
      run("ProvidedInjectedClassesWithMatchingTypeKeysAreReportedAsWarnings.kt");
    }

    @Test
    @TestMetadata("ProvidedInjectedClassesWithMatchingTypeKeysButDifferentScopesAreOk.kt")
    public void testProvidedInjectedClassesWithMatchingTypeKeysButDifferentScopesAreOk() {
      run("ProvidedInjectedClassesWithMatchingTypeKeysButDifferentScopesAreOk.kt");
    }

    @Test
    @TestMetadata("ProvidesCannotHaveReceivers_AbstractClass.kt")
    public void testProvidesCannotHaveReceivers_AbstractClass() {
      run("ProvidesCannotHaveReceivers_AbstractClass.kt");
    }

    @Test
    @TestMetadata("ProvidesCannotHaveReceivers_Interface.kt")
    public void testProvidesCannotHaveReceivers_Interface() {
      run("ProvidesCannotHaveReceivers_Interface.kt");
    }

    @Test
    @TestMetadata("ProvidesCannotLiveInObjects.kt")
    public void testProvidesCannotLiveInObjects() {
      run("ProvidesCannotLiveInObjects.kt");
    }

    @Test
    @TestMetadata("ProvidesFunctionsCannotBeTopLevel.kt")
    public void testProvidesFunctionsCannotBeTopLevel() {
      run("ProvidesFunctionsCannotBeTopLevel.kt");
    }

    @Test
    @TestMetadata("ProvidesMustHaveABody_AbstractClass.kt")
    public void testProvidesMustHaveABody_AbstractClass() {
      run("ProvidesMustHaveABody_AbstractClass.kt");
    }

    @Test
    @TestMetadata("ProvidesMustHaveABody_Interface.kt")
    public void testProvidesMustHaveABody_Interface() {
      run("ProvidesMustHaveABody_Interface.kt");
    }

    @Test
    @TestMetadata("ProvidesMustHaveExplicitReturnTypes.kt")
    public void testProvidesMustHaveExplicitReturnTypes() {
      run("ProvidesMustHaveExplicitReturnTypes.kt");
    }

    @Test
    @TestMetadata("ProvidesNamesMustBeUniqueInContainer.kt")
    public void testProvidesNamesMustBeUniqueInContainer() {
      run("ProvidesNamesMustBeUniqueInContainer.kt");
    }

    @Test
    @TestMetadata("ProvidesNamesMustBeUniqueInGraph.kt")
    public void testProvidesNamesMustBeUniqueInGraph() {
      run("ProvidesNamesMustBeUniqueInGraph.kt");
    }

    @Test
    @TestMetadata("ProvidesPropertiesCannotBeMutable.kt")
    public void testProvidesPropertiesCannotBeMutable() {
      run("ProvidesPropertiesCannotBeMutable.kt");
    }

    @Test
    @TestMetadata("ProvidesShouldBePrivate_InAbstractClass.kt")
    public void testProvidesShouldBePrivate_InAbstractClass() {
      run("ProvidesShouldBePrivate_InAbstractClass.kt");
    }

    @Test
    @TestMetadata("ProvidesShouldBePrivate_InInterface.kt")
    public void testProvidesShouldBePrivate_InInterface() {
      run("ProvidesShouldBePrivate_InInterface.kt");
    }

    @Test
    @TestMetadata("ProvidesWithExtensionsAndNonThisReturningBodiesShouldError.kt")
    public void testProvidesWithExtensionsAndNonThisReturningBodiesShouldError() {
      run("ProvidesWithExtensionsAndNonThisReturningBodiesShouldError.kt");
    }

    @Test
    @TestMetadata("Provides_AbstractClass_MayNotHaveTypeParameters.kt")
    public void testProvides_AbstractClass_MayNotHaveTypeParameters() {
      run("Provides_AbstractClass_MayNotHaveTypeParameters.kt");
    }

    @Test
    @TestMetadata("Provides_ElementsIntoSet_AllowsIntrinsicElementType.kt")
    public void testProvides_ElementsIntoSet_AllowsIntrinsicElementType() {
      run("Provides_ElementsIntoSet_AllowsIntrinsicElementType.kt");
    }

    @Test
    @TestMetadata("Provides_Interface_MayNotHaveTypeParameters.kt")
    public void testProvides_Interface_MayNotHaveTypeParameters() {
      run("Provides_Interface_MayNotHaveTypeParameters.kt");
    }

    @Test
    @TestMetadata("Provides_ReturnTypeCannotBeIntrinsic.kt")
    public void testProvides_ReturnTypeCannotBeIntrinsic() {
      run("Provides_ReturnTypeCannotBeIntrinsic.kt");
    }

    @Test
    @TestMetadata("Provides_ReturnTypeCannotBeIntrinsic_DaggerInterop.kt")
    public void testProvides_ReturnTypeCannotBeIntrinsic_DaggerInterop() {
      run("Provides_ReturnTypeCannotBeIntrinsic_DaggerInterop.kt");
    }

    @Test
    @TestMetadata("ScopedConstantProvider.kt")
    public void testScopedConstantProvider() {
      run("ScopedConstantProvider.kt");
    }

    @Test
    @TestMetadata("ScopedConstantProviderInliningDisabled.kt")
    public void testScopedConstantProviderInliningDisabled() {
      run("ScopedConstantProviderInliningDisabled.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/rich")
  @TestDataPath("$PROJECT_ROOT")
  public class Rich {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/rich/" + fileName);
    }

    @Test
    public void testAllFilesPresentInRich() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/rich"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("DependencyCycleRich.kt")
    public void testDependencyCycleRich() {
      run("DependencyCycleRich.kt");
    }

    @Test
    @TestMetadata("DuplicateBindingsRich.kt")
    public void testDuplicateBindingsRich() {
      run("DuplicateBindingsRich.kt");
    }

    @Test
    @TestMetadata("MissingBindingRich.kt")
    public void testMissingBindingRich() {
      run("MissingBindingRich.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/diagnostic/suspend")
  @TestDataPath("$PROJECT_ROOT")
  public class Suspend {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/diagnostic/suspend/" + fileName);
    }

    @Test
    public void testAllFilesPresentInSuspend() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic/suspend"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("AssistedFactorySuspendMemberDep.kt")
    public void testAssistedFactorySuspendMemberDep() {
      run("AssistedFactorySuspendMemberDep.kt");
    }

    @Test
    @TestMetadata("AssistedFactorySuspendRequired.kt")
    public void testAssistedFactorySuspendRequired() {
      run("AssistedFactorySuspendRequired.kt");
    }

    @Test
    @TestMetadata("BindingFromNonSuspendAccessor.kt")
    public void testBindingFromNonSuspendAccessor() {
      run("BindingFromNonSuspendAccessor.kt");
    }

    @Test
    @TestMetadata("BindingWrappedInLazy.kt")
    public void testBindingWrappedInLazy() {
      run("BindingWrappedInLazy.kt");
    }

    @Test
    @TestMetadata("BindingWrappedInProvider.kt")
    public void testBindingWrappedInProvider() {
      run("BindingWrappedInProvider.kt");
    }

    @Test
    @TestMetadata("BindingWrappedInProviderAccessor.kt")
    public void testBindingWrappedInProviderAccessor() {
      run("BindingWrappedInProviderAccessor.kt");
    }

    @Test
    @TestMetadata("BindsIsNotAllowed.kt")
    public void testBindsIsNotAllowed() {
      run("BindsIsNotAllowed.kt");
    }

    @Test
    @TestMetadata("DaggerInteropDaggerLazyWrapsSuspend.kt")
    public void testDaggerInteropDaggerLazyWrapsSuspend() {
      run("DaggerInteropDaggerLazyWrapsSuspend.kt");
    }

    @Test
    @TestMetadata("DaggerInteropJakartaProviderWrapsSuspend.kt")
    public void testDaggerInteropJakartaProviderWrapsSuspend() {
      run("DaggerInteropJakartaProviderWrapsSuspend.kt");
    }

    @Test
    @TestMetadata("DaggerInteropJavaxProviderWrapsSuspend.kt")
    public void testDaggerInteropJavaxProviderWrapsSuspend() {
      run("DaggerInteropJavaxProviderWrapsSuspend.kt");
    }

    @Test
    @TestMetadata("DepInConstructorInjectedNonSuspendAccessor.kt")
    public void testDepInConstructorInjectedNonSuspendAccessor() {
      run("DepInConstructorInjectedNonSuspendAccessor.kt");
    }

    @Test
    @TestMetadata("DesugaredSuspendProviderWarning.kt")
    public void testDesugaredSuspendProviderWarning() {
      run("DesugaredSuspendProviderWarning.kt");
    }

    @Test
    @TestMetadata("DuplicateKeyAccessors.kt")
    public void testDuplicateKeyAccessors() {
      run("DuplicateKeyAccessors.kt");
    }

    @Test
    @TestMetadata("GraphExtensionParentSuspendBindingFromNonSuspendAccessor.kt")
    public void testGraphExtensionParentSuspendBindingFromNonSuspendAccessor() {
      run("GraphExtensionParentSuspendBindingFromNonSuspendAccessor.kt");
    }

    @Test
    @TestMetadata("IncludedGraphDeferredAccessorFromNonSuspendAccessor.kt")
    public void testIncludedGraphDeferredAccessorFromNonSuspendAccessor() {
      run("IncludedGraphDeferredAccessorFromNonSuspendAccessor.kt");
    }

    @Test
    @TestMetadata("IncludedGraphSuspendAccessorFromNonSuspendAccessor.kt")
    public void testIncludedGraphSuspendAccessorFromNonSuspendAccessor() {
      run("IncludedGraphSuspendAccessorFromNonSuspendAccessor.kt");
    }

    @Test
    @TestMetadata("MemberInjectingClassWithSuspendCtorDep.kt")
    public void testMemberInjectingClassWithSuspendCtorDep() {
      run("MemberInjectingClassWithSuspendCtorDep.kt");
    }

    @Test
    @TestMetadata("MemberInjectingClassWithSuspendCtorDepFromBinary.kt")
    public void testMemberInjectingClassWithSuspendCtorDepFromBinary() {
      run("MemberInjectingClassWithSuspendCtorDepFromBinary.kt");
    }

    @Test
    @TestMetadata("MemberInjectionOverSuspendBinding.kt")
    public void testMemberInjectionOverSuspendBinding() {
      run("MemberInjectionOverSuspendBinding.kt");
    }

    @Test
    @TestMetadata("MissingRuntimeCoroutinesForNestedSuspendLazy.kt")
    public void testMissingRuntimeCoroutinesForNestedSuspendLazy() {
      run("MissingRuntimeCoroutinesForNestedSuspendLazy.kt");
    }

    @Test
    @TestMetadata("MissingRuntimeCoroutinesForNestedSuspendLazyInInjectedFunction.kt")
    public void testMissingRuntimeCoroutinesForNestedSuspendLazyInInjectedFunction() {
      run("MissingRuntimeCoroutinesForNestedSuspendLazyInInjectedFunction.kt");
    }

    @Test
    @TestMetadata("MissingRuntimeCoroutinesForScopedBinding.kt")
    public void testMissingRuntimeCoroutinesForScopedBinding() {
      run("MissingRuntimeCoroutinesForScopedBinding.kt");
    }

    @Test
    @TestMetadata("MixedCauseTransitiveSuspend.kt")
    public void testMixedCauseTransitiveSuspend() {
      run("MixedCauseTransitiveSuspend.kt");
    }

    @Test
    @TestMetadata("MultibindsIsNotAllowed.kt")
    public void testMultibindsIsNotAllowed() {
      run("MultibindsIsNotAllowed.kt");
    }

    @Test
    @TestMetadata("ScalarMapMultibindingOverSuspendValues.kt")
    public void testScalarMapMultibindingOverSuspendValues() {
      run("ScalarMapMultibindingOverSuspendValues.kt");
    }

    @Test
    @TestMetadata("SetMultibindingOverSuspendElements.kt")
    public void testSetMultibindingOverSuspendElements() {
      run("SetMultibindingOverSuspendElements.kt");
    }

    @Test
    @TestMetadata("SuspendProvidersDisabled.kt")
    public void testSuspendProvidersDisabled() {
      run("SuspendProvidersDisabled.kt");
    }

    @Test
    @TestMetadata("SuspendProvidersDisabledAcrossModules.kt")
    public void testSuspendProvidersDisabledAcrossModules() {
      run("SuspendProvidersDisabledAcrossModules.kt");
    }

    @Test
    @TestMetadata("UnsupportedSuspendMapValue.kt")
    public void testUnsupportedSuspendMapValue() {
      run("UnsupportedSuspendMapValue.kt");
    }
  }
}
