

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/fir")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/dump/fir/" + fileName);
  }

  @Test
  public void testAllFilesPresentInFir() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("contributionProvidersShouldNotGenerateForContributesTo.kt")
  public void testContributionProvidersShouldNotGenerateForContributesTo() {
    run("contributionProvidersShouldNotGenerateForContributesTo.kt");
  }

  @Test
  @TestMetadata("InjectCtorAlwaysUsedEvenIfClassAnnotated_k23x.kt")
  public void testInjectCtorAlwaysUsedEvenIfClassAnnotated_k23x() {
    run("InjectCtorAlwaysUsedEvenIfClassAnnotated_k23x.kt");
  }

  @Test
  @TestMetadata("InjectCtorAlwaysUsedEvenIfClassAnnotated_k24x.kt")
  public void testInjectCtorAlwaysUsedEvenIfClassAnnotated_k24x() {
    run("InjectCtorAlwaysUsedEvenIfClassAnnotated_k24x.kt");
  }

  @Test
  @TestMetadata("scratch.kt")
  public void testScratch() {
    run("scratch.kt");
  }

  @Test
  @TestMetadata("TopLevelComposableHiddenFromObjC_k23x.kt")
  public void testTopLevelComposableHiddenFromObjC_k23x() {
    run("TopLevelComposableHiddenFromObjC_k23x.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/fir/aggregation")
  @TestDataPath("$PROJECT_ROOT")
  public class Aggregation {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/fir/aggregation/" + fileName);
    }

    @Test
    public void testAllFilesPresentInAggregation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/fir/aggregation"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ContributingGraphExtensions_k23x.kt")
    public void testContributingGraphExtensions_k23x() {
      run("ContributingGraphExtensions_k23x.kt");
    }

    @Test
    @TestMetadata("ContributingGraphExtensions_k24x.kt")
    public void testContributingGraphExtensions_k24x() {
      run("ContributingGraphExtensions_k24x.kt");
    }

    @Test
    @TestMetadata("ContributingTypesDependency_k23x.kt")
    public void testContributingTypesDependency_k23x() {
      run("ContributingTypesDependency_k23x.kt");
    }

    @Test
    @TestMetadata("ContributingTypesDependency_k24x.kt")
    public void testContributingTypesDependency_k24x() {
      run("ContributingTypesDependency_k24x.kt");
    }

    @Test
    @TestMetadata("ContributingTypes_k23x.kt")
    public void testContributingTypes_k23x() {
      run("ContributingTypes_k23x.kt");
    }

    @Test
    @TestMetadata("ContributingTypes_k24x.kt")
    public void testContributingTypes_k24x() {
      run("ContributingTypes_k24x.kt");
    }

    @Test
    @TestMetadata("FirHintGenerationWithIrClasses.kt")
    public void testFirHintGenerationWithIrClasses() {
      run("FirHintGenerationWithIrClasses.kt");
    }

    @Test
    @TestMetadata("FirHintGenerationWorks_k23x.kt")
    public void testFirHintGenerationWorks_k23x() {
      run("FirHintGenerationWorks_k23x.kt");
    }
  }
}
