

package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/dump/ir")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  private void run(String fileName) {
    runTest("compiler-tests/src/test/data/dump/ir/" + fileName);
  }

  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AssistedInjectClassFactoriesGetReused.kt")
  public void testAssistedInjectClassFactoriesGetReused() {
    run("AssistedInjectClassFactoriesGetReused.kt");
  }

  @Test
  @TestMetadata("GeneratedCompanionSupertypes.kt")
  public void testGeneratedCompanionSupertypes() {
    run("GeneratedCompanionSupertypes.kt");
  }

  @Test
  @TestMetadata("MultibindingsHaveConsistentOrderAcrossContributedGraph.kt")
  public void testMultibindingsHaveConsistentOrderAcrossContributedGraph() {
    run("MultibindingsHaveConsistentOrderAcrossContributedGraph.kt");
  }

  @Test
  @TestMetadata("MultibindingsWithComplexDependenciesGetProperties.kt")
  public void testMultibindingsWithComplexDependenciesGetProperties() {
    run("MultibindingsWithComplexDependenciesGetProperties.kt");
  }

  @Test
  @TestMetadata("scratch.kt")
  public void testScratch() {
    run("scratch.kt");
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/aggregation")
  @TestDataPath("$PROJECT_ROOT")
  public class Aggregation {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/aggregation/" + fileName);
    }

    @Test
    public void testAllFilesPresentInAggregation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/aggregation"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ChunkMergedSupertypes.kt")
    public void testChunkMergedSupertypes() {
      run("ChunkMergedSupertypes.kt");
    }

    @Test
    @TestMetadata("ContributionProviders_BasicDump.kt")
    public void testContributionProviders_BasicDump() {
      run("ContributionProviders_BasicDump.kt");
    }

    @Test
    @TestMetadata("ContributionProviders_ScopedMultipleBindings.kt")
    public void testContributionProviders_ScopedMultipleBindings() {
      run("ContributionProviders_ScopedMultipleBindings.kt");
    }

    @Test
    @TestMetadata("ContributorsWithSameSimpleNames.kt")
    public void testContributorsWithSameSimpleNames() {
      run("ContributorsWithSameSimpleNames.kt");
    }

    @Test
    @TestMetadata("ContributorsWithSameSimpleNamesSameOrigin.kt")
    public void testContributorsWithSameSimpleNamesSameOrigin() {
      run("ContributorsWithSameSimpleNamesSameOrigin.kt");
    }

    @Test
    @TestMetadata("DefaultBindingMirror.kt")
    public void testDefaultBindingMirror() {
      run("DefaultBindingMirror.kt");
    }

    @Test
    @TestMetadata("ImplicitClassKeyPopulatedOnCopy.kt")
    public void testImplicitClassKeyPopulatedOnCopy() {
      run("ImplicitClassKeyPopulatedOnCopy.kt");
    }

    @Test
    @TestMetadata("MergeContributionsInIrOptIn.kt")
    public void testMergeContributionsInIrOptIn() {
      run("MergeContributionsInIrOptIn.kt");
    }

    @Test
    @TestMetadata("MultipleContributionsOnlyProduceOneHintFile.kt")
    public void testMultipleContributionsOnlyProduceOneHintFile() {
      run("MultipleContributionsOnlyProduceOneHintFile.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/cycles")
  @TestDataPath("$PROJECT_ROOT")
  public class Cycles {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/cycles/" + fileName);
    }

    @Test
    public void testAllFilesPresentInCycles() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/cycles"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("BindsCycleGraph.kt")
    public void testBindsCycleGraph() {
      run("BindsCycleGraph.kt");
    }

    @Test
    @TestMetadata("CycleGraph.kt")
    public void testCycleGraph() {
      run("CycleGraph.kt");
    }

    @Test
    @TestMetadata("CycleMapGraph.kt")
    public void testCycleMapGraph() {
      run("CycleMapGraph.kt");
    }

    @Test
    @TestMetadata("SelfCycle.kt")
    public void testSelfCycle() {
      run("SelfCycle.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph")
  @TestDataPath("$PROJECT_ROOT")
  public class Dependencygraph {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/" + fileName);
    }

    @Test
    public void testAllFilesPresentInDependencygraph() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CreatorParamsDoNotGetChunked.kt")
    public void testCreatorParamsDoNotGetChunked() {
      run("CreatorParamsDoNotGetChunked.kt");
    }

    @Test
    @TestMetadata("DeepGraphExtensionChainUsesHashedNames.kt")
    public void testDeepGraphExtensionChainUsesHashedNames() {
      run("DeepGraphExtensionChainUsesHashedNames.kt");
    }

    @Test
    @TestMetadata("EmptyMapMultibindingsUseEmptyMap.kt")
    public void testEmptyMapMultibindingsUseEmptyMap() {
      run("EmptyMapMultibindingsUseEmptyMap.kt");
    }

    @Test
    @TestMetadata("ExtensionsAreInnerClasses.kt")
    public void testExtensionsAreInnerClasses() {
      run("ExtensionsAreInnerClasses.kt");
    }

    @Test
    @TestMetadata("GraphAccessors.kt")
    public void testGraphAccessors() {
      run("GraphAccessors.kt");
    }

    @Test
    @TestMetadata("GraphImplClassAsReturnType.kt")
    public void testGraphImplClassAsReturnType() {
      run("GraphImplClassAsReturnType.kt");
    }

    @Test
    @TestMetadata("InitsAreChunked.kt")
    public void testInitsAreChunked() {
      run("InitsAreChunked.kt");
    }

    @Test
    @TestMetadata("InlinedObjectProviderUsesGeneratedFactory.kt")
    public void testInlinedObjectProviderUsesGeneratedFactory() {
      run("InlinedObjectProviderUsesGeneratedFactory.kt");
    }

    @Test
    @TestMetadata("InlinedObjectSuspendProvidersUseGeneratedFactory.kt")
    public void testInlinedObjectSuspendProvidersUseGeneratedFactory() {
      run("InlinedObjectSuspendProvidersUseGeneratedFactory.kt");
    }

    @Test
    @TestMetadata("LazyPropertiesHaveDeterministicOrder.kt")
    public void testLazyPropertiesHaveDeterministicOrder() {
      run("LazyPropertiesHaveDeterministicOrder.kt");
    }

    @Test
    @TestMetadata("MapBuildersUseInlineInstantiation.kt")
    public void testMapBuildersUseInlineInstantiation() {
      run("MapBuildersUseInlineInstantiation.kt");
    }

    @Test
    @TestMetadata("MapsUseMapBuilderIfNoProvider.kt")
    public void testMapsUseMapBuilderIfNoProvider() {
      run("MapsUseMapBuilderIfNoProvider.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAcrossMultipleMultis.kt")
    public void testMixedUseFactoryAcrossMultipleMultis() {
      run("MixedUseFactoryAcrossMultipleMultis.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAcrossMultipleNestedMiddleMultis.kt")
    public void testMixedUseFactoryAcrossMultipleNestedMiddleMultis() {
      run("MixedUseFactoryAcrossMultipleNestedMiddleMultis.kt");
    }

    @Test
    @TestMetadata("MixedUseFactoryAndScalarRefsShouldUseOneProviderField.kt")
    public void testMixedUseFactoryAndScalarRefsShouldUseOneProviderField() {
      run("MixedUseFactoryAndScalarRefsShouldUseOneProviderField.kt");
    }

    @Test
    @TestMetadata("MultipleRefsGetProviderFields.kt")
    public void testMultipleRefsGetProviderFields() {
      run("MultipleRefsGetProviderFields.kt");
    }

    @Test
    @TestMetadata("NestedClassNamesInDump.kt")
    public void testNestedClassNamesInDump() {
      run("NestedClassNamesInDump.kt");
    }

    @Test
    @TestMetadata("OptionalBindingsHaveValidFieldNames.kt")
    public void testOptionalBindingsHaveValidFieldNames() {
      run("OptionalBindingsHaveValidFieldNames.kt");
    }

    @Test
    @TestMetadata("PrimitiveProviderFactoryParamUsesPrimitiveFactory.kt")
    public void testPrimitiveProviderFactoryParamUsesPrimitiveFactory() {
      run("PrimitiveProviderFactoryParamUsesPrimitiveFactory.kt");
    }

    @Test
    @TestMetadata("ProviderAccessorsAreTrackedInRefCounting.kt")
    public void testProviderAccessorsAreTrackedInRefCounting() {
      run("ProviderAccessorsAreTrackedInRefCounting.kt");
    }

    @Test
    @TestMetadata("RefCountingFollowsAliases.kt")
    public void testRefCountingFollowsAliases() {
      run("RefCountingFollowsAliases.kt");
    }

    @Test
    @TestMetadata("ReusableScalarBindings.kt")
    public void testReusableScalarBindings() {
      run("ReusableScalarBindings.kt");
    }

    @Test
    @TestMetadata("RuntimeTracing.kt")
    public void testRuntimeTracing() {
      run("RuntimeTracing.kt");
    }

    @Test
    @TestMetadata("UnusedInstanceBindingsInUnextendedGraphGetNoProviderFields.kt")
    public void testUnusedInstanceBindingsInUnextendedGraphGetNoProviderFields() {
      run("UnusedInstanceBindingsInUnextendedGraphGetNoProviderFields.kt");
    }

    @Test
    @TestMetadata("UnusedScopedBindingsInUnextendedGraphGetNoProviderFields.kt")
    public void testUnusedScopedBindingsInUnextendedGraphGetNoProviderFields() {
      run("UnusedScopedBindingsInUnextendedGraphGetNoProviderFields.kt");
    }

    @Test
    @TestMetadata("UnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered.kt")
    public void testUnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered() {
      run("UnusedScopedConstructorInjectedClassWithConstructorAnnotatedIsDiscovered.kt");
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic")
    @TestDataPath("$PROJECT_ROOT")
    public class Dynamic {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic/" + fileName);
      }

      @Test
      public void testAllFilesPresentInDynamic() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/dynamic"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("SimpleDynamicGraph.kt")
      public void testSimpleDynamicGraph() {
        run("SimpleDynamicGraph.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/interop")
    @TestDataPath("$PROJECT_ROOT")
    public class Interop {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/interop/" + fileName);
      }

      @Test
      public void testAllFilesPresentInInterop() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/interop"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("BindsOptionalOfUsesLazyProviders.kt")
      public void testBindsOptionalOfUsesLazyProviders() {
        run("BindsOptionalOfUsesLazyProviders.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/membernaming")
    @TestDataPath("$PROJECT_ROOT")
    public class Membernaming {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/membernaming/" + fileName);
      }

      @Test
      public void testAllFilesPresentInMembernaming() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/membernaming"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("MinimalMemberNamingAcrossShards.kt")
      public void testMinimalMemberNamingAcrossShards() {
        run("MinimalMemberNamingAcrossShards.kt");
      }

      @Test
      @TestMetadata("TypedMemberNamingOnSimpleGraph.kt")
      public void testTypedMemberNamingOnSimpleGraph() {
        run("TypedMemberNamingOnSimpleGraph.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding")
    @TestDataPath("$PROJECT_ROOT")
    public class Sharding {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding/" + fileName);
      }

      @Test
      public void testAllFilesPresentInSharding() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/sharding"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("CrossShardDependencies.kt")
      public void testCrossShardDependencies() {
        run("CrossShardDependencies.kt");
      }

      @Test
      @TestMetadata("MinimalGraphSharding.kt")
      public void testMinimalGraphSharding() {
        run("MinimalGraphSharding.kt");
      }

      @Test
      @TestMetadata("MinimalGraphShardingDisabled.kt")
      public void testMinimalGraphShardingDisabled() {
        run("MinimalGraphShardingDisabled.kt");
      }

      @Test
      @TestMetadata("MinimalGraphShardingTooSmall.kt")
      public void testMinimalGraphShardingTooSmall() {
        run("MinimalGraphShardingTooSmall.kt");
      }

      @Test
      @TestMetadata("ShardedGraphWithChainedExtensions.kt")
      public void testShardedGraphWithChainedExtensions() {
        run("ShardedGraphWithChainedExtensions.kt");
      }

      @Test
      @TestMetadata("ShardedGraphWithMultipleExtensions.kt")
      public void testShardedGraphWithMultipleExtensions() {
        run("ShardedGraphWithMultipleExtensions.kt");
      }

      @Test
      @TestMetadata("ShardingWithBinds.kt")
      public void testShardingWithBinds() {
        run("ShardingWithBinds.kt");
      }

      @Test
      @TestMetadata("ShardingWithChunkedInit.kt")
      public void testShardingWithChunkedInit() {
        run("ShardingWithChunkedInit.kt");
      }

      @Test
      @TestMetadata("ShardingWithCycle.kt")
      public void testShardingWithCycle() {
        run("ShardingWithCycle.kt");
      }

      @Test
      @TestMetadata("ShardingWithMultibindings.kt")
      public void testShardingWithMultibindings() {
        run("ShardingWithMultibindings.kt");
      }

      @Test
      @TestMetadata("ShardingWithProvides.kt")
      public void testShardingWithProvides() {
        run("ShardingWithProvides.kt");
      }

      @Test
      @TestMetadata("ThreeShardsWithOrder.kt")
      public void testThreeShardsWithOrder() {
        run("ThreeShardsWithOrder.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders")
    @TestDataPath("$PROJECT_ROOT")
    public class Switchingproviders {
      private void run(String fileName) {
        runTest("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders/" + fileName);
      }

      @Test
      public void testAllFilesPresentInSwitchingproviders() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/dependencygraph/switchingproviders"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("ChunkedSwitchingProvider.kt")
      public void testChunkedSwitchingProvider() {
        run("ChunkedSwitchingProvider.kt");
      }

      @Test
      @TestMetadata("SimpleSwitchingProvider.kt")
      public void testSimpleSwitchingProvider() {
        run("SimpleSwitchingProvider.kt");
      }

      @Test
      @TestMetadata("SimpleSwitchingProviderWithShards.kt")
      public void testSimpleSwitchingProviderWithShards() {
        run("SimpleSwitchingProviderWithShards.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersAcrossExtensions.kt")
      public void testSwitchingProvidersAcrossExtensions() {
        run("SwitchingProvidersAcrossExtensions.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithBindsOptional.kt")
      public void testSwitchingProvidersWithBindsOptional() {
        run("SwitchingProvidersWithBindsOptional.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithCycles.kt")
      public void testSwitchingProvidersWithCycles() {
        run("SwitchingProvidersWithCycles.kt");
      }

      @Test
      @TestMetadata("SwitchingProvidersWithMembersInjectProvider.kt")
      public void testSwitchingProvidersWithMembersInjectProvider() {
        run("SwitchingProvidersWithMembersInjectProvider.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/ic")
  @TestDataPath("$PROJECT_ROOT")
  public class Ic {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/ic/" + fileName);
    }

    @Test
    public void testAllFilesPresentInIc() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/ic"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CreatorSignatureCarriers.kt")
    public void testCreatorSignatureCarriers() {
      run("CreatorSignatureCarriers.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/injectconstructor")
  @TestDataPath("$PROJECT_ROOT")
  public class Injectconstructor {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/injectconstructor/" + fileName);
    }

    @Test
    public void testAllFilesPresentInInjectconstructor() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/injectconstructor"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ConstructorFunctionSignatures.kt")
    public void testConstructorFunctionSignatures() {
      run("ConstructorFunctionSignatures.kt");
    }

    @Test
    @TestMetadata("DefaultValuesPropagateToNewInstanceParams.kt")
    public void testDefaultValuesPropagateToNewInstanceParams() {
      run("DefaultValuesPropagateToNewInstanceParams.kt");
    }

    @Test
    @TestMetadata("SuspendConstructorInjection.kt")
    public void testSuspendConstructorInjection() {
      run("SuspendConstructorInjection.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/multibindings")
  @TestDataPath("$PROJECT_ROOT")
  public class Multibindings {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/multibindings/" + fileName);
    }

    @Test
    public void testAllFilesPresentInMultibindings() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/multibindings"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ElementsIntoSetWorkInScalars.kt")
    public void testElementsIntoSetWorkInScalars() {
      run("ElementsIntoSetWorkInScalars.kt");
    }

    @Test
    @TestMetadata("ElementsIntoSetWorkInScalarsMixed.kt")
    public void testElementsIntoSetWorkInScalarsMixed() {
      run("ElementsIntoSetWorkInScalarsMixed.kt");
    }

    @Test
    @TestMetadata("InjectorFunctionsDoNotTriggerProviderGets.kt")
    public void testInjectorFunctionsDoNotTriggerProviderGets() {
      run("InjectorFunctionsDoNotTriggerProviderGets.kt");
    }

    @Test
    @TestMetadata("MapProvidersParticipateInProviderRefcounting.kt")
    public void testMapProvidersParticipateInProviderRefcounting() {
      run("MapProvidersParticipateInProviderRefcounting.kt");
    }

    @Test
    @TestMetadata("MultibindingInParentMemberInjectedClass.kt")
    public void testMultibindingInParentMemberInjectedClass() {
      run("MultibindingInParentMemberInjectedClass.kt");
    }

    @Test
    @TestMetadata("MultibindingProviderAccessPropagatesRefCount.kt")
    public void testMultibindingProviderAccessPropagatesRefCount() {
      run("MultibindingProviderAccessPropagatesRefCount.kt");
    }

    @Test
    @TestMetadata("MultibindingRefCountFromFactoryPath.kt")
    public void testMultibindingRefCountFromFactoryPath() {
      run("MultibindingRefCountFromFactoryPath.kt");
    }

    @Test
    @TestMetadata("MultibindingSourcesGetGettersThroughAliases.kt")
    public void testMultibindingSourcesGetGettersThroughAliases() {
      run("MultibindingSourcesGetGettersThroughAliases.kt");
    }

    @Test
    @TestMetadata("MultibindingSourcesGetRefcountedViaFactoryPath.kt")
    public void testMultibindingSourcesGetRefcountedViaFactoryPath() {
      run("MultibindingSourcesGetRefcountedViaFactoryPath.kt");
    }

    @Test
    @TestMetadata("SingletonMapFactory.kt")
    public void testSingletonMapFactory() {
      run("SingletonMapFactory.kt");
    }

    @Test
    @TestMetadata("SingletonMapLazyFactory.kt")
    public void testSingletonMapLazyFactory() {
      run("SingletonMapLazyFactory.kt");
    }

    @Test
    @TestMetadata("SingletonMapProviderFactory.kt")
    public void testSingletonMapProviderFactory() {
      run("SingletonMapProviderFactory.kt");
    }

    @Test
    @TestMetadata("SingletonMapProviderLazyFactory.kt")
    public void testSingletonMapProviderLazyFactory() {
      run("SingletonMapProviderLazyFactory.kt");
    }

    @Test
    @TestMetadata("SingletonSetFactory.kt")
    public void testSingletonSetFactory() {
      run("SingletonSetFactory.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/provides")
  @TestDataPath("$PROJECT_ROOT")
  public class Provides {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/provides/" + fileName);
    }

    @Test
    public void testAllFilesPresentInProvides() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/provides"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("DefaultValuesPropagateToNewInstanceParams.kt")
    public void testDefaultValuesPropagateToNewInstanceParams() {
      run("DefaultValuesPropagateToNewInstanceParams.kt");
    }

    @Test
    @TestMetadata("InlineStatusIsPropagated.kt")
    public void testInlineStatusIsPropagated() {
      run("InlineStatusIsPropagated.kt");
    }

    @Test
    @TestMetadata("InlinedProviderIsComptimeOnly.kt")
    public void testInlinedProviderIsComptimeOnly() {
      run("InlinedProviderIsComptimeOnly.kt");
    }

    @Test
    @TestMetadata("JvmFieldProvidersUseFieldAccess.kt")
    public void testJvmFieldProvidersUseFieldAccess() {
      run("JvmFieldProvidersUseFieldAccess.kt");
    }

    @Test
    @TestMetadata("PrivateProviderPropertyMirror.kt")
    public void testPrivateProviderPropertyMirror() {
      run("PrivateProviderPropertyMirror.kt");
    }

    @Test
    @TestMetadata("ProviderInliningDisabled.kt")
    public void testProviderInliningDisabled() {
      run("ProviderInliningDisabled.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-tests/src/test/data/dump/ir/visibility")
  @TestDataPath("$PROJECT_ROOT")
  public class Visibility {
    private void run(String fileName) {
      runTest("compiler-tests/src/test/data/dump/ir/visibility/" + fileName);
    }

    @Test
    public void testAllFilesPresentInVisibility() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/dump/ir/visibility"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("DaggerProviderVisibility.kt")
    public void testDaggerProviderVisibility() {
      run("DaggerProviderVisibility.kt");
    }

    @Test
    @TestMetadata("DaggerProviderVisibilityDifferentModule.kt")
    public void testDaggerProviderVisibilityDifferentModule() {
      run("DaggerProviderVisibilityDifferentModule.kt");
    }

    @Test
    @TestMetadata("InternalVisibility.kt")
    public void testInternalVisibility() {
      run("InternalVisibility.kt");
    }

    @Test
    @TestMetadata("InternalVisibilityDifferentModule.kt")
    public void testInternalVisibilityDifferentModule() {
      run("InternalVisibilityDifferentModule.kt");
    }

    @Test
    @TestMetadata("ProtectedVisibility.kt")
    public void testProtectedVisibility() {
      run("ProtectedVisibility.kt");
    }
  }
}
